=== CharlyGH/dia2sql/data/project.dtd
<!ELEMENT project (item+)>

<!ELEMENT item       EMPTY>
<!ATTLIST item name  CDATA #REQUIRED
               value CDATA #REQUIRED
               info  CDATA #IMPLIED>

=== CharlyGH/dia2sql/xml/project.xml
<?xml version='1.0'?>
<!DOCTYPE project SYSTEM 'project.dtd'>
<project>
  <item name="tablespace-root" value="/var/lib/postgresql/18"/>
  <item name="valid-from"      value="gueltig_ab"      info=""           color=""/>
  <item name="valid-to"        value="gueltig_bis"     info=""           color=""/>
  <item name="base"            value="base_{}"         info="writable"   color="red"/>
  <item name="const"           value="const_{}"        info="writable"   color="darkgreen"/>
  <item name="dim"             value="dim_{}"          info="writable"   color="blue"/>
  <item name="fact"            value="fakt_{}"         info="writable"   color="black"/>
  <item name="hist"            value="hist_{}"         info="readable"   color="purple"/>
  <item name="id-type"         value="integer"         info="sequence"   color=""/>
  <item name="id-max"          value="2147483647"      info="sequence"   color=""/>
</project>
